### ISSUE TITLE
powershell process loads the system very heavily in victim PC

### ISSUE THREAD

**Issue by Ondrik8** [r00t-3xp10it/meterpeter#11]
Intel i7 8 core

![Screenshot_1](https://user-images.githubusercontent.com/59111771/88051897-181cde00-cb62-11ea-9dda-2269dcd8715a.png)

**Comment by r00t-3xp10it** [comment]
I can **`reduce the CPU load`** by calling just one **`powershell process`** to exec commands .. but ....
- Executing diferent tasks (commands) using child (background) processes ... its one AV evasion technic ..
  (Thats one of the reasons why sometimes the main process its **PS** the child **CMD**, the other child **VBS**, etc ..)
