### ISSUE TITLE
Some trouble with 216`s line

### ISSUE THREAD

**Issue by ru000** [r00t-3xp10it/meterpeter#12]
https://github.com/r00t-3xp10it/meterpeter/blob/f956ed248137169bfdc790bcedf1ab07e1f5a7de/meterpeter.ps1#L216

Hello Mate! So look please at this screen:
![error1](https://user-images.githubusercontent.com/23490060/88823967-9d853b80-d1bd-11ea-8fed-69ed36d1715b.png)
I see this red-alert inside the console of my Kali Linux after typing next command: 
```
cd meterpeter
pwsh -File meterpeter.ps1
```

<br />

And after that, I see the next process, but, unfortunately, I can not get the final result and connection with my testing PC:
![error2](https://user-images.githubusercontent.com/23490060/88823987-a544e000-d1bd-11ea-91ee-06bfcb8b8f56.png)
Could an error in the execution of line 216 affect the absence of a result in the end?
If this is critical, what steps should be taken?

**Comment by ru000** [comment]
IDK will be good this info or no, but I use in my system the "ifconfig" command. 
For example, https://prnt.sc/tqkvr5 So maybe you can use it to best understanding my problem
Thank you for attention

**Comment by r00t-3xp10it** [comment]
that should not been giving one error ..
because **`$localIpAddress`** variable its trigger everytime the user **`dont input is ip address`** in meterpeter prompt ..
If the ip address its input then meterpeter will not use the **`$localIpAddress`** variable declaration ..

**Comment by ru000** [comment]
@r00t-3xp10it 
My friend, a little update from me:
I think you shouldn't look for the problem in your code. So the problem is because I used your tools on the wrong operating system. I tested a lot and came up with this result:
I replaced line 216 from the original state:
`$localIpAddress = ((ipconfig | findstr [0-9]. \.) [0]). Split () [- 1]`
and now line 216 looks like
`$localIpAddress = ((ifconfig | grep [0-9]. \.) [0]). Split () [- 1]`
After these changes, all errors disappeared. 
But I will test your new updated version too! Thank you for being there. It helped me

**Comment by r00t-3xp10it** [comment]
thanks for your help ..
i will update sourcecode soon with this changes ...

**HINT:** `$localIpAddress = ((ifconfig | grep [0-9]. \.) [0]). Split () [- 1]` <-- LINUX .. ipconfig <--- WINDOWS ..
i need to add the two variables to the sourcecode ..
