### ISSUE TITLE
The problem with the connection to the remote PC

### ISSUE THREAD

**Issue by ru000** [r00t-3xp10it/meterpeter#13]
I have integrated the executable file on the remote testing desktop.
The file was encrypted by **all AV software** In short, this all about the **Cob@ltStr1ke + Meterpeter**._

The work was **completed successfully** and I got a stable permanent connection to the computer under test
and configured the session data transmission every 200 minutes (beacon home)

But during one of the sessions, the **connection was broken** (connection with my testing PC). The AV and WF did not work on the computer, since this PC is **in front of me** and I know it. And the PC is **constantly online**. But I still can't get the activity of the working session again. Do you know what the problem might be and can I solve it with your commands and modules? (I am looked at all logs and not found problems. The connection was cut off without reason.)

This is a specific question that is not a bug and not related to the performance of your tools.
I attempt to find a solution to kill the problem. Sorry, that takes time.

And the last available info which I see is:
![bug1](https://user-images.githubusercontent.com/23490060/88935909-295c9d80-d27a-11ea-948c-6e215e518a8b.png)

**Comment by r00t-3xp10it** [comment]
### Let's see if i understand your problem ...

<br />

- 1º - you have used **`meterpeter C2`** to create the **`Client.ps1`**
- 2º - you have used **`meterpeter C2`** + **[`ps2exe.ps1`](https://github.com/r00t-3xp10it/meterpeter/tree/master/PS2EXE)** to compile the **`client.ps1`** to **`client.exe`**

<br />

**Remark:** PS2EXE does not really convert PS scripts to standalone executables ..
what it really does its to create a **`C++`** program and then use the **`.NET`** framework to compile it to executable ..
**( I have been facing bugs also using the compiled executable with meterpeter mimratz post-scripts )**

<br />

Thats the reason why iam starting to writte a new **[`WIKI`](https://github.com/r00t-3xp10it/meterpeter/wiki/meterpeter---client-standalone-executable)** to describe this kind of issues ..
About **`beacon home`** we can use **`schtasks`** native appl to beacon home from **`xx`** to **`xx`** minutes of interval:
[meterpeter - working with remote tasks](https://github.com/r00t-3xp10it/meterpeter/wiki/Working-with-Remote-Tasks---Using-Schtasks-Native-Appl#schtasks---create-remote-task)

**Comment by ru000** [comment]
1º and 2º -- completely **yes**

_About **`beacon home`** we can use **`schtasks`** native appl to beacon home from **`xx`** to **`xx`** minutes of interval:_

https://prnt.sc/triujn
https://prnt.sc/triwke
Yes, I did the following manipulations with the remote PC and for some time it still "rang" every 3 hours and the session was active inside the C0b@ltStr1ke even after the computer was restarted. But at some point, the session disappeared from coba1t and the remote computer no longer rings to my Linux server.  And I don't understand what could have gone wrong.

**Comment by r00t-3xp10it** [comment]
### Possible causes

- 1º - Schtasks.exe in some systems its configurated to NOT run tasks under battery usage.
![err](https://user-images.githubusercontent.com/23490060/88999706-3070c380-d2ed-11ea-88af-2567ef85967d.png)

- 2º - AV daylly check migth have deleted task or payload ..
- 3º - the standalone executable created by PS2EXE malfunctions ...

---

And .. the 2º screenshot **`Its a Privilege escalation technic rigth ??`**
maybee the vulnerable process have stoped after restart ..
