### ISSUE TITLE
Autorun script on initial connection

### ISSUE THREAD

**Issue by honeyfairy** [r00t-3xp10it/meterpeter#16]
It would be good if we could autorun Persistence and any custom command on initial connection from client.
Is there functionality already available in this script for this perhaps ?

**Comment by honeyfairy** [comment]
Anyone?

**Comment by r00t-3xp10it** [comment]
Persistence: https://github.com/r00t-3xp10it/meterpeter/wiki/Persist-Remote-Client-script-Using-Beacon-(loop)
Schtasks: https://github.com/r00t-3xp10it/meterpeter/wiki/Working-with-Remote-Tasks---Using-Schtasks-Native-Appl
