### ISSUE TITLE
path issues on parrot 

### ISSUE THREAD

**Issue by tchach0** [r00t-3xp10it/meterpeter#19]
Copy-Item: /home/glitch/meterpeter/meterpeter.ps1:469
Line |
 469 |         Copy-Item -Path "/Get-Content -Path $Bin$Dropper_Name.bat -Raw) -Replace "Char. …
     |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path '/home/glitch/meterpeter/mimiRatz/BACKUP.bat'.

Get-Content: /home/glitch/meterpeter/meterpeter.ps1:471
Line |
 471 |         ((Get-Content -Path $Bin$Dropper_Name.bat -Raw) -Replace "Char …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path '/home/glitch/meterpeter/mimiRatz/Update-KB5005101.bat' because it does not exist.

[i] Make dropper spawn UAC dialog to run elevated? (y|n):

**Comment by r00t-3xp10it** [comment]
its meterpeter installed in `/home/glitch/meterpeter` ???

**Comment by tchach0** [comment]
Yes

**Comment by r00t-3xp10it** [comment]
I belive your error its on the `COPY` command ...

<br />

1º chose one existing file for testing

Open a `powershell` console and execute:
```powersell
Copy-Item -Path "/root/FileChosen.sh" -Destination "/root/test/FileChosen.sh"|Out-Null
```

Then tell me if the command successfuly Copy the file

**Comment by tchach0** [comment]
Thanks I will try fratelo
